### ISSUE TITLE
hard coding of guild_id

### ISSUE THREAD

**Issue by jonigirl** [27Saumya/Yuki#2]
rather then:
`@youtube.command(guild_ids=[824969244860088332, 847740349853073418, 865962392093851658, 896457384552202312, 918802666790993951], description="Download a youtube video!")`

Just asking why this are not set in a .env, this would allow just one place and you could just:

```
# system
import os

# .env configuration
from dotenv import load_dotenv
load_dotenv()

@youtube.command(guild_ids=os.getenv("GUILDIDS"), description="Download a youtube video!")

```

**Comment by saumsy** [comment]
ohh ya thanks @jonigirl for the recommendation.. but I just changed it to global slash :)

**Comment by jonigirl** [comment]
Even better
